name: Cluster deployment

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job started"
      - run: |
          sleep 300
      - run: |
          echo "Job finished"

