name: Pull request create or resync

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --tags origin 
      - name: Get commits in PR
        id: get_commits
        run: |
          BASE_SHA=$(git rev-parse origin/${{ github.base_ref }}^2)
          echo $BASE_SHA
          HEAD_SHA=$(git rev-parse origin/${{ github.head_ref }})
          echo $HEAD_SHA
          COMMIT_LIST=$(git rev-list --ancestry-path ${BASE_SHA}..${HEAD_SHA})
          COMMIT_LIST="${COMMIT_LIST//'%'/'%25'}"
          COMMIT_LIST="${COMMIT_LIST//$'\n'/'%0A'}"
          COMMIT_LIST="${COMMIT_LIST//$'\r'/'%0D'}"
          echo "::set-output name=commits::${COMMIT_LIST}"
      - name: Get code version tag in scope of PR (latest/if any)
        id: get_latest_code_tag
        run: |
          TAGS=$(echo "${{ steps.get_commits.outputs.commits }}" | while read COMMIT; do git describe --tags --match="v[0-9]*\.[0-9]*\.[0-9]*" --exact-match  ${COMMIT} 2>/dev/null || true; done)
          echo "::set-output name=latest_code_tag::${TAGS}"
      - name: Get changed files
        id: get_changed_files
        run: |
          DIFF=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})
          echo "Diff between ${{ github.base_ref }} and ${{ github.sha }}"
          echo "$DIFF"
          DIFF="${DIFF//'%'/'%25'}"
          DIFF="${DIFF//$'\n'/'%0A'}"
          DIFF="${DIFF//$'\r'/'%0D'}"
          echo "::set-output name=files::${DIFF}"
      - name: Files scope
        id: files_scope
        run: |
          CODE_FILES=$(echo "${{ steps.get_changed_files.outputs.files }}" | while read FILE; do echo ${FILE}|grep "^code\/*" || true; done)
          echo "Code files:${CODE_FILES}"
          CODE_FILES="${CODE_FILES//'%'/'%25'}"
          CODE_FILES="${CODE_FILES//$'\n'/'%0A'}"
          CODE_FILES="${CODE_FILES//$'\r'/'%0D'}"
          echo "::set-output name=code_files::${CODE_FILES}"
          CONF_FILES=$(echo "${{ steps.get_changed_files.outputs.files }}" | while read FILE; do echo ${FILE}|grep "^config\/*" || true; done)
          echo "Configuration files:${CONF_FILES}"
          CONF_FILES="${CONF_FILES//'%'/'%25'}"
          CONF_FILES="${CONF_FILES//$'\n'/'%0A'}"
          CONF_FILES="${CONF_FILES//$'\r'/'%0D'}"
          echo "::set-output name=conf_files::${CONF_FILES}"
          WORKFLOW_FILES=$(echo "${{ steps.get_changed_files.outputs.files }}" | while read FILE; do echo ${FILE}|grep "^\.github\/workflows\/*" || true; done)
          echo "Workflow files:${WORKFLOW_FILES}"
          WORKFLOW_FILES="${WORKFLOW_FILES//'%'/'%25'}"
          WORKFLOW_FILES="${WORKFLOW_FILES//$'\n'/'%0A'}"
          WORKFLOW_FILES="${WORKFLOW_FILES//$'\r'/'%0D'}"
          echo "::set-output name=workflow_files::${WORKFLOW_FILES}"
      - run: |
          echo "latest code tag in current PR"
          echo ${{ steps.get_latest_code_tag.outputs.latest_code_tag }}
          echo "latest code tag overall"
          git describe --tags  $(git rev-list --tags="v[0-9]*\.[0-9]*\.[0-9]*" --max-count=1)
          echo "latest release tag overall"
          git describe --tags  $(git rev-list --tags="release-[0-9]*\.[0-9]*\.[0-9]*" --max-count=1)
      - name: Check code version tag presense
        run: |
          if [[ -n "${{ steps.files_scope.outputs.code_files }}" && -z "${{ steps.get_latest_code_tag.outputs.latest_code_tag }}" ]]; then
            echo "Pull request should contain at least one commit with the version tag if code files are changed"
            echo "Files changed: ${{ steps.files_scope.outputs.code_files }}"
            exit 1
          else
            echo "Code version tag presense check passed"
            echo "Files changed: ${{ steps.files_scope.outputs.code_files }}"
            echo "Code version: ${{ steps.get_latest_code_tag.outputs.latest_code_tag }}"
          fi
      - name: Check that github workflow changes are separate from code/configuration
        run: |
          if [[ ( -n "${{ steps.files_scope.outputs.code_files }}" || -n "${{ steps.files_scope.outputs.conf_files }}" ) && -n "${{ steps.files_scope.outputs.workflow_files }}" ]]; then
            echo "Pull request should not contain workflow modifications together with code/configuration modifications"
            echo "Code files changed: ${{ steps.files_scope.outputs.code_files }}"
            echo "Configuration files changed: ${{ steps.files_scope.outputs.conf_files }}"
            echo "Workflow files changed: ${{ steps.files_scope.outputs.workflow_files }}"
            exit 1
          else
            echo "Workflow separation check passed"
            echo "Code files changed: ${{ steps.files_scope.outputs.code_files }}"
            echo "Configuration files changed: ${{ steps.files_scope.outputs.conf_files }}"
            echo "Workflow files changed: ${{ steps.files_scope.outputs.workflow_files }}"
          fi


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Get changed files
        id: file_changes
        run: |
          DIFF=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})
          echo "Diff between ${{ github.base_ref }} and ${{ github.sha }}"
          echo "$DIFF"
          echo "::set-output name=files::$( echo "$DIFF" | xargs echo )"    
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0
        env:
          SKIP: no-commit-to-branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extra_args: --color=always --show-diff-on-failure --files ${{ steps.file_changes.outputs.files }}
        
  context-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

